#-------------------------------
# General Site Settings

title: Diamond Hall
email: DiamondHallevents@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Capacity, value: '9'}
- {name: Food, value: '7'}
- {name: Reception, value: '10'}
- {name: Security, value: '6'}
- {name: Parking, value: '7'}
- {name: Location, value: '5'}
- {name: Entertainment, value: '8'}
- {name: Staff, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Wedding June 2015 , folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Party August 2015, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Expo September 2015, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: New Year Eve 2015, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Wedding January 2016, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Party January 2016, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Retirement February 2016, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Wedding February 2016, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-married.jpg',
  name: 'Matt & Dominique',
  title: 'Just married',
  quote: '<p><strong>blablbalblablablallb</strong>addsiaodjasiodjasiodjaidaj odajiansdanodasmd o</p>',
  logo: 'logo1.png'}
- {avatar: 'face-talk.jpg',
  name: 'Hank Lee',
  title: 'Sony Conference, Mediamont Int.',
  quote: '<p><strong>jfoasjdiajdaspokadapsodk</strong>asdkpasdkpoakdw faibiad nasoasdpaoskda topo</p>',
  logo: 'logo2.png'}
- {avatar: 'face-party.jpg',
  name: 'Rebecca & Veronica',
  title: 'Social Media Girl',
  quote: '<p><strong>Yea, adkapskdoasd</strong> àspdlas`dplwl`pal dwoaidmiwoan ieuhredda</p>',
  logo: 'logo3.png'}
- {avatar: 'face-mom.jpg',
  name: 'Cassidy Michaels',
  title: 'Proud mother',
  quote: '<p><strong>asdaspdokwpaw</strong>apsodkasodkadnwiuand moierpdaok</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com'}
- {icon: 'facebook', link: 'https://facebook.com'}
- {icon: 'google-plus', link: 'https://www.plus.google.com'}
- {icon: 'youtube', link: 'https://www.youtube.com'}
- {icon: 'instagram', link: 'http://www.instagram.com'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
